version: '2'

services:
  app:
    restart: always
    build: ./backend
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
  nginx-reverse-proxy:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
